"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const electron = require("electron");
electron.contextBridge.exposeInMainWorld("electron", {
    openFileDialogHandler: async () => await ipcInvoke("openFileDialog"),
    getCollectionsHandler: async () => await ipcInvoke("getCollections"),
    createCollectionHandler: async (collection) => await ipcInvoke("createCollection", collection),
    deleteCollectionHandler: async (collection) => await ipcInvoke("deleteCollection", collection),
    updateCollectionHandler: async (collection) => await ipcInvoke("updateCollection", collection),
    getMoviesHandler: async () => await ipcInvoke("getMovies"),
    createMovieHandler: async (movie) => await ipcInvoke("createMovie", movie),
    deleteMovieHandler: async (movie) => await ipcInvoke("deleteMovie", movie),
    updateMovieHandler: async (movie) => await ipcInvoke("updateMovie", movie),
    getShowsHandler: async () => await ipcInvoke("getShows"),
    createShowHandler: async (show) => await ipcInvoke("createShow", show),
    deleteShowHandler: async (show) => await ipcInvoke("deleteShow", show),
    updateShowHandler: async (show) => await ipcInvoke("updateShow", show),
    getShortsHandler: async () => await ipcInvoke("getShorts"),
    createShortHandler: async (short) => await ipcInvoke("createShort", short),
    deleteShortHandler: async (short) => await ipcInvoke("deleteShort", short),
    updateShortHandler: async (short) => await ipcInvoke("updateShort", short),
    getMusicHandler: async () => await ipcInvoke("getMusic"),
    createMusicHandler: async (music) => await ipcInvoke("createMusic", music),
    deleteMusicHandler: async (music) => await ipcInvoke("deleteMusic", music),
    updateMusicHandler: async (music) => await ipcInvoke("updateMusic", music),
    getCommercialsHandler: async () => await ipcInvoke("getCommercials"),
    createCommercialHandler: async (commercial) => await ipcInvoke("createCommercial", commercial),
    deleteCommercialHandler: async (commercial) => await ipcInvoke("deleteCommercial", commercial),
    updateCommercialHandler: async (commercial) => await ipcInvoke("updateCommercial", commercial),
    getPromosHandler: async () => await ipcInvoke("getPromos"),
    createPromoHandler: async (promo) => await ipcInvoke("createPromo", promo),
    deletePromoHandler: async (promo) => await ipcInvoke("deletePromo", promo),
    updatePromoHandler: async (promo) => await ipcInvoke("updatePromo", promo),
    getBumpersHandler: async () => await ipcInvoke("getBumpers"),
    createBumperHandler: async (bumper) => await ipcInvoke("createBumper", bumper),
    deleteBumperHandler: async (bumper) => await ipcInvoke("deleteBumper", bumper),
    updateBumperHandler: async (bumper) => await ipcInvoke("updateBumper", bumper),
    getAestheticTagsHandler: async () => await ipcInvoke("getAestheticTags"),
    createAestheticTagHandler: async (tag) => await ipcInvoke("createAestheticTag", tag),
    deleteAestheticTagHandler: async (tag) => await ipcInvoke("deleteAestheticTag", tag),
    getEraTagsHandler: async () => await ipcInvoke("getEraTags"),
    createEraTagHandler: async (tag) => await ipcInvoke("createEraTag", tag),
    deleteEraTagHandler: async (tag) => await ipcInvoke("deleteEraTag", tag),
    getGenreTagsHandler: async () => await ipcInvoke("getGenreTags"),
    createGenreTagHandler: async (tag) => await ipcInvoke("createGenreTag", tag),
    deleteGenreTagHandler: async (tag) => await ipcInvoke("deleteGenreTag", tag),
    getSpecialtyTagsHandler: async () => await ipcInvoke("getSpecialtyTags"),
    createSpecialtyTagHandler: async (tag) => await ipcInvoke("createSpecialtyTag", tag),
    deleteSpecialtyTagHandler: async (tag) => await ipcInvoke("deleteSpecialtyTag", tag),
    getAgeGroupsHandler: async () => await ipcInvoke("getAgeGroups"),
    createAgeGroupHandler: async (tag) => await ipcInvoke("createAgeGroup", tag),
    deleteAgeGroupHandler: async (tag) => await ipcInvoke("deleteAgeGroup", tag),
    updateAgeGroupHandler: async (tag) => await ipcInvoke("updateAgeGroup", tag),
    getHolidaysHandler: async () => await ipcInvoke("getHolidays"),
    createHolidayHandler: async (tag) => await ipcInvoke("createHoliday", tag),
    deleteHolidayHandler: async (tag) => await ipcInvoke("deleteHoliday", tag),
    updateHolidayHandler: async (tag) => await ipcInvoke("updateHoliday", tag),
    getMusicGenresHandler: async () => await ipcInvoke("getMusicGenres"),
    createMusicGenreHandler: async (tag) => await ipcInvoke("createMusicGenre", tag),
    deleteMusicGenreHandler: async (tag) => await ipcInvoke("deleteMusicGenre", tag),
});
function ipcInvoke(key, ...args) {
    return electron.ipcRenderer.invoke(key, ...args);
}
function ipcOn(key, callback) {
    electron.ipcRenderer.on(key, (_, payload) => callback(payload));
}
