export const normalizationDefaults = {
  FIRST_ANCHOR_SAFETY_MARGIN_SEC: 120,
  MIN_OPENING_BUFFER_SEC: 300,
  TARGET_OPENING_BUFFER_SEC: 900,
  MAX_OPENING_BUFFER_SEC: 1500,
  ANCHOR_SELECTION_LOOKAHEAD_COUNT: 12,

  REMUX_ESTIMATE_SEC: 5,
  TRANSCODE_SPEED_SD_X: 6.0,
  TRANSCODE_SPEED_HD_X: 2.5,
  TRANSCODE_SPEED_UHD_X: 0.8,
  TRANSCODE_ESTIMATE_OVERHEAD_SEC: 20,

  CACHE_MAX_SIZE_GB: 300,
  CACHE_SOFT_WATERMARK: 0.8,
  CACHE_HARD_WATERMARK: 0.9,
  CACHE_CRITICAL_WATERMARK: 0.95,
  CACHE_TARGET_AFTER_EVICT: 0.75,
  MIN_FREE_DISK_GB: 20,
  EVICTION_BATCH_GB: 10,

  PINNED_NOW_WINDOW_HOURS: 4,
  PINNED_SOON_WINDOW_HOURS: 24,
  WARM_RECENCY_DAYS: 14,
  COLD_RECENCY_DAYS: 45,
  REUSE_WINDOW_DAYS: 30,

  DRIFT_TOLERANCE_SEC: 3,
  DRIFT_SOFT_CORRECTION_SEC: 12,
  DRIFT_HARD_CORRECTION_SEC: 45,
  MAX_FILLER_ADJUST_PER_BOUNDARY_SEC: 120,
  REALIGNMENT_LOOKAHEAD_BLOCKS: 3,

  NORMALIZATION_WORKERS: 1,
  MAX_IN_FLIGHT_PER_SOURCE: 1,
  STATUS_LOG_INTERVAL_SEC: 30,
  EVICTION_CHECK_INTERVAL_MIN: 10,
  ADMISSION_RECHECK_INTERVAL_SEC: 15,
} as const;

export type NormalizationDefaults = typeof normalizationDefaults;
